plugins {
    id 'java'
    id 'application'
}

group = 'com.oose'
version = '1.0.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.mysql:mysql-connector-j:9.3.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'com.oose.labsafety.LabSafetyApplication'
    applicationDefaultJvmArgs = [
        '-Dfile.encoding=UTF-8',
        '-Dsun.stdout.encoding=UTF-8',
        '-Dsun.stderr.encoding=UTF-8'
    ]
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
